config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :devices
  resources :reparos
  resources :foto

  get '/aparelhos/slug/:slug', to: 'devices#showBySlug' ,:as => :aparelhos_slug
  get '/aparelhos/id/:id', to: 'devices#showById' ,:as => :aparelhos_id
  get '/aparelhos', to: 'devices#index'

  get "/reparos/id/:id", to: "reparos#showById", :as => :reparos_id
  get "/reparos/slug/:slug", to: "reparos#showBySlug", :as => :reparo_slug
  get "/reparos/aparelhos/:tipo", to: "reparos#showByDeviceTipo", :as => :reparo_aparelho_tipo
  get "/reparos/marca/:marca", to: "reparos#showByDeviceMarca", :as => :reparo_aparelho_marca
  get "/reparos/tipo/:tipo", to: "reparos#showByTipo", :as => :reparo_tipo
  

  root 'welcomes#index'

end

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <ul>
        <li><h3>Conteúdo</h3></li>
        <li><%=link_to "Reparos de Aparelhos", reparos_path%></li>
        <li><%=link_to "Nossos Serviços","/servicos/"%></li>
        <li><%=link_to "Nossos Produtos", "/produtos/"%></li>
        <li><%=link_to "Sobre Nós", "/sobre-nos"%></li>
        <li><%=link_to "Contato", "/contato/"%></li>
    </ul>
    <ul>
      <li><h3>Reparos mais vistos</h3></li>
      <%@reparosMaisVistos.each do |reparo|%>
        <li><%=link_to reparo.nome, reparo_slug_path(reparo.slug)%></li>
      <% end %>
      <li><%=link_to "Todos os Reparos", reparos_path%></li>
    </ul>
    <ul>
      <li><h3>Siga a gente</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Fale com agente</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>

  </div>

  

  <p>Todos os direitos reservados</p>
</footer>

app/views/partials/_nav.html.erb
<header class="navigation">
  <div class="navigation-wrapper">

    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <div class="nav">
      <ul id="navigation-menu">
        
        <li class="logo">
          
          <%= link_to image_tag("logo-home.png", size: "256x114"), "/" %>

        </li>

        <li class="nav-link more"><a href="javascript:void(0)">Reparos de Aparelhos</a>
          <ul class="submenu">
            <li><%=link_to "Celulares e SmartPhones", reparo_aparelho_tipo_path("smartphones")%></li>
            <li><%=link_to "Tablets",reparo_aparelho_tipo_path("tablets")%></li>

              <li class="more"><a href="javascript:void(0)">Apple</a>
              <ul class="submenu">
                <% @reparosApple.each do |reparo|%>
                  <li><%=link_to reparo.nome, reparo_slug_path(reparo.slug)%></li>
                 <% end %>
                <li><%=link_to "Mais...", reparo_aparelho_marca_path("apple")%></li>
              </ul>
            </li>

            <li class="more"><a href="javascript:void(0)">Samsung</a>
              <ul class="submenu">
                <% @reparosSamsung.each do |reparo|%>
                  <li><%=link_to reparo.nome, reparo_slug_path(reparo.slug)%></li>
                <% end %>
                <li><%=link_to "Mais...", reparo_aparelho_marca_path("samsung")%></li>
              </ul>
            </li>

          </ul>
        </li>
        
        <li class="nav-link"><%=link_to "Nossos Serviços","/servicos/"%></li>
        <li class="nav-link"><%=link_to "Nossos Produtos", "/produtos/"%></li>
        <li class="nav-link"><%=link_to "Sobre Nós", "/sobre-nos"%></li>
        <li class="nav-link"><%=link_to "Contato", "/contato/"%></li>
      </ul>
    </div>
    <div class="navigation-tools">

      
    </div>
  </div>
</header>

app/views/partials/_nav2.html.erb
<header class="centered-navigation">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="">
    </a>
    <a href="" class="centered-navigation-menu-button">MENU</a>
    <ul class="centered-navigation-menu">
      
            <li class="nav-link logo">
        <a href="javascript:void(0)" class="logo">
          <%=image_tag "logo-home.png"%>
        </a>
      </li>
      <li class="nav-link more"><a href="javascript:void(0)">Reparos</a>
        <ul class="submenu">
          <li><a href="javascript:void(0)">Submenu Item</a></li>
          <li><a href="javascript:void(0)">Another Item</a></li>
          <li class="more"><a href="javascript:void(0)">Item with submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
              <li><a href="javascript:void(0)">Another Item</a></li>
            </ul>
          </li>
          <li class="more"><a href="javascript:void(0)">Another submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu</a></li>
              <li><a href="javascript:void(0)">An Item</a></li>
            </ul>
          </li>
        </ul>
      </li>

      <li class="nav-link"><a href="javascript:void(0)">Serviços</a></li>
      <li class="nav-link"><a href="javascript:void(0)">Produtos</a></li>


      <li class="nav-link"><a href="javascript:void(0)">Sobre Nós</a></li>
      <li class="nav-link more"><a href="javascript:void(0)">More</a>
        <ul class="submenu">
          <li><a href="javascript:void(0)">Submenu Item</a></li>
          <li><a href="javascript:void(0)">Another Item</a></li>
          <li class="more"><a href="javascript:void(0)">Item with submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
              <li><a href="javascript:void(0)">Another Item</a></li>
            </ul>
          </li>
          <li class="more"><a href="javascript:void(0)">Another submenu</a>
            <ul class="submenu">
              <li><a href="javascript:void(0)">Sub-submenu</a></li>
              <li><a href="javascript:void(0)">An Item</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="nav-link"><a href="javascript:void(0)">Contato</a></li>
    </ul>
  </div>
</header>

app/views/partials/_pagination.html.erb
<br>


<div class="pagination">
  <ul>
    <li class="page-prev"><a href="javascript:void(0)">Prev</a></li>
    <li>
      <ul>
        <li><a href="javascript:void(0)">1</a></li>
        <li><a href="javascript:void(0)">2</a></li>
        <li><a href="javascript:void(0)">3</a></li>
        <li><a href="javascript:void(0)">4</a></li>
        <li><a href="javascript:void(0)">5</a></li>
        <li><a href="javascript:void(0)">6</a></li>
        <li><a href="javascript:void(0)">7</a></li>
      </ul>
    </li>
    <li class="page-next"><a href="javascript:void(0)">Next</a></li>
  </ul>
</div>

<br>