config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :devices
  resources :reparos
  resources :foto

  get '/aparelhos/slug/:slug', to: 'devices#showBySlug' ,:as => :aparelhos_slug
  get '/aparelhos/id/:id', to: 'devices#showById' ,:as => :aparelhos_id
  get '/aparelhos', to: 'devices#index'

  get "/reparos/id/:id", to: "reparos#showById", :as => :reparos_id
  get "/reparos/slug/:slug", to: "reparos#showBySlug", :as => :reparo_slug
  get "/reparos/aparelhos/:tipo", to: "reparos#showByDeviceTipo", :as => :reparo_aparelho_tipo
  get "/reparos/marca/:marca", to: "reparos#showByDeviceMarca", :as => :reparo_aparelho_marca
  get "/reparos/tipo/:tipo", to: "reparos#showByTipo", :as => :reparo_tipo
  

  root 'welcomes#index'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  ##
	# Bussiness Logic
	##

  ##
	# Show all Published photos, ordered by update_at: :desc
	##
	def self.published(pagina=1)
		@tmp = where(published:true)
								.order(updated_at: :desc)
								.page pagina
		return @tmp
	end

	##
	# Show Published photo with the given slug.
	##
	def self.slug(slug)
		@temp = where(published:true)
						.find_by slug: slug
		return @temp
	end

	##
	# Paperclip config
	##
	has_attached_file :image,
	:styles => {
		:banner => "1024x768",
		:normal => "256x256",
		:thumb => "128x128#"
	},
	:convert_options => {
		:thumb => "-quality 75 -strip",
		:normal => "-quality 80 -strip",
		:banner => "-quality 80 -strip"
	},
	:default_url => "/images/question-mark.jpg"

	##
	# Validações
	##

	# Validate file size
	validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 3.megabytes, :message => "A imagem deve ter menos de um megabyte."
	# Validate content type
	validates_attachment_content_type :image, :content_type => /\Aimage/
	# Validate filename
	validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/]

	##
	# Associações
	##

	belongs_to :reparo


##
#
##
  ##
  # Declarações de Filtros
  ##
  # before_save :create_permalink


  ##
	# Private stuff
	##
	private

	def create_permalink
	  # self.slug = title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
	end
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @foto }
      else
        format.html { render action: 'new' }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:titulo, :descricao, :published)
    end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<h1>Listing fotos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= foto.titulo %></td>
        <td><%= foto.descricao %></td>
        <td><%= foto.published %></td>
        <td><%= link_to 'Show', foto %></td>
        <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
        <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @foto.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @foto.descricao %>
</p>

<p>
  <strong>Published:</strong>
  <%= @foto.published %>
</p>

<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>